# Generated by Django 3.2.10 on 2024-11-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/imgs', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/imgs', verbose_name='Изображение'),
        ),
    ]
