# Generated by Django 3.2.10 on 2024-11-30 23:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RemoveField(
            model_name='news',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='news',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='news',
            name='content_image',
            field=models.ImageField(null=True, upload_to='content_imgs', verbose_name='Фон для блока новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст новости:'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать новость'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(null=True, upload_to='news-imgs', verbose_name='Изображение для новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateField(auto_now_add=True, default='2024-01-01', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=ckeditor.fields.RichTextField(help_text='Вы можете использовать HTML или стилизовать текст с разными цветами.'),
        ),
    ]
