# Generated by Django 3.2.10 on 2024-12-01 02:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20241130_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст новости:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(help_text='Вы можете использовать HTML или стилизовать текст с разными цветами.'),
        ),
    ]
